[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
pidfile=/var/run/supervisord.pid
user=root

[program:postgresql]
command=/start-postgres.sh
autostart=true
autorestart=true
startretries=10
startsecs=3
stdout_logfile=/var/log/postgresql.log
stderr_logfile=/var/log/postgresql_err.log
priority=100

[program:librephotos]
command=/start-librephotos.sh
directory=/code
autostart=true
autorestart=true
startretries=10
startsecs=10
stdout_logfile=/var/log/librephotos.log
stderr_logfile=/var/log/librephotos_err.log
priority=200
environment=
    SERVE_FRONTEND="true",
    DB_BACKEND="postgresql",
    DB_NAME="librephotos",
    DB_USER="librephotos",
    DB_PASS="%(ENV_DB_PASS)s",
    DB_HOST="127.0.0.1",
    DB_PORT="5432",
    BACKEND_HOST="127.0.0.1",
    SECRET_KEY="%(ENV_SECRET_KEY)s",
    ALLOWED_HOSTS="*",
    CSRF_TRUSTED_ORIGINS="%(ENV_CSRF_TRUSTED_ORIGINS)s",
    WEB_CONCURRENCY="%(ENV_WORKERS)s",
    DEBUG="0",
    ADMIN_USERNAME="%(ENV_ADMIN_USERNAME)s",
    ADMIN_PASSWORD="%(ENV_ADMIN_PASSWORD)s",
    ADMIN_EMAIL="%(ENV_ADMIN_EMAIL)s"
